apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: admin-pod
  name: admin-pod
spec:
  containers:
  - image: busybox
    name: admin-pod
    command: ['sh', '-c', 'sleep 3600']
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
