apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: green-nginx
  name: green-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: green-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
