apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxprod
  name: nginxprod
  namespace: production
spec:
  containers:
  - image: nginx
    name: nginxprod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
