apiVersion: v1
kind: ServiceAccount
metadata:
  name: sam-acct
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sam-role
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "deployments"
      - "secrets"
      - "configmap"
    verbs:
      - "create"
      - "delete"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: sam-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sam-role
subjects:
  - kind: ServiceAccount
    name: sam-acct
    namespace: default
