apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
    - name: init-original
      image: busybox
      command: ['sh','-c','echo This is real app && sleep 4800']
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh','-c','echo waiting for connection && sleep 1600']