apiVersion: v1
kind: Pod
metadata:
  name: cka-pod
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /usr/bin/nginx/html
      name: cache-volume
  initContainers:
  - image: devopstitan/cka-exam:init
    name: titan
    command: ["sh","-c","echo" , "Hello World" ,">","/data/index.html"]
    volumeMounts:
    - mountPath: /data/
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
