apiVersion: v1
kind:  Pod
metadata:
  name: mycoolwabapp
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: mycoolwaebapp2
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
