apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-pod
  name: multi-pod
  namespace: devlopment
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: redis
    name: redis
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
