apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: immutable
  name: immutable
spec:
  containers:
  - image: httpd
    name: immutable
    volumeMounts:
      - name: edir
        mountPath: /usr/local/apache2/logs
    resources: {}
    securityContext:
      readOnlyRootFilesystem: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: edir
      emptyDir: {}
status: {}
