apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tesk4deploy
  name: tesk4deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tesk4deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tesk4deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
