apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  api-key: random
  password: admin
---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: web-app
    image: busybox
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: api-key
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: password
  - name: secrets-init
    image: busybox
    command: ["sh", "-c", "cp /api-key /secrets && cp /password /secrets"]
    volumeMounts:
    - name: secret-volume
      mountPath: /secrets
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secrets
