apiVersion: v1
kind: Pod
metadata:
  name: non-root-user-container
  namespace: k29
spec:
  serviceAccountName: sa-gov
  containers:
  - image: bitnami/nginx:1.21.6
    name: secured-container
    securityContext:
      runAsNonRoot: true