apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ready-if-service-ready
  name: ready-if-service-ready
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: ready-if-service-ready
    livenessProbe:
      exec:
        command:
         - 'true'
    readinessProbe:
       exec:
         command:
         - 'sh'
         - '-c'
         - ' wget -T2 -O- http://service-am-i-ready:80'
