apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: safari
  name: safari
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safari
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: safari
    spec:
      containers:
      - image: httpd
        imagePullPolicy: IfNotPresent
        name: httpd
      volumeMounts:
      - mountPath: "/volume/data"
        name: safaripod
     volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: safari-pvc
