apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: dev
    tier: front
  name: delta-pod
spec:
  containers:
  - image: nginx:1.17
    name: delta-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
