apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: audit-web-app
  name: audit-web-app
spec:
  containers:
  - image: nginx
    name: audit-web-app
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
