apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-jxc56fv
  name: pod-jxc56fv
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - image: redis:alpine
    name: pod-jxc56fv
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
