apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pinku-role-binding
  namespace: argo
subjects:
- kind: User
  name: pinku
  apiGroup: rbac.authorization.k8s.io
roleRef:
   kind: Role
   name: pinku-role
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: pinku-role
rules:
  - apiGroups: ["","apps","extensions"]
    resources: ["pods","deployments","services","ingress"]
    verbs: ["get","watch","list"]