apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2022-04-17T14:36:45Z"
  name: developer
  namespace: blue
  resourceVersion: "2648"
  uid: c7f88c5b-0b22-41c9-91d7-c6ea418dc177
rules:
- apiGroups:
  - ""
  resourceNames:
  - dark-blue-app
  resources:
  - pods
  verbs:
  - get
  - watch
  - create
  - delete