apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  containers:
  - command:
    - sh
    - -c
    - ping google.fr
    image: bash
    name: app
    resources: {}
    securityContext:
        runAsUser: 1000
status: {}
