apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  annotations:
        container.apparmor.security.beta.kubernetes.io/armor: localhost/docker-nginx
  labels:
    run: armor
  name: armor
spec:
  containers:
  - image: nginx
    name: armor
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
