apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-non-root-user-non-privileged
spec:
  privileged: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
  - '*'