apiVersion: v1
kind: Pod
metadata:
  name: redispod
spec:
  containers:
    - name: redispod
      image: redis
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: type
              operator: In
              values:
                - database
                - db
  tolerations:
    - key: "nodetype"
      value: "database"
      operator: "Equal"
      effect: "NoSchedule"




