apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: dbvol
spec:
    storageClassName: sc-provisoner
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 0.5Gi