apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/volume/nginx"
  capacity:
    storage: 1Gi
