apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeName: log-volume
  resources:
    requests:
      storage: 200Mi
